# Chạy ứng dụng trên port 8080
server:
  port: 8080

# Bỏ tính năng cache của thymeleaf để lập trình cho nhanh
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  messages:
    basename: i18n/messages
  web:
    locale: vi
  jpa:
    hibernate:
      ddl-auto: update
